# NRF Project - Makefile(Golang)
# Copyright(C) 2019-2025, Team Gorgeous Bubble, All Rights Reserved.

# Golang
GO = go
GO-BUILD = $(GO) build
GO-CLEAN = $(GO) clean
GO-TEST = $(GO) test
GO-GET = $(GO) get

all: test

test:
	$(GO-TEST) -v -cover -benchmem -bench .